// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY2AEpJZ683-KiPFZOBajZ9RM9yqWO1pY',
    appId: '1:774209885887:web:bd9d34f301367e6502180a',
    messagingSenderId: '774209885887',
    projectId: 'portfolio-bae40',
    authDomain: 'portfolio-bae40.firebaseapp.com',
    storageBucket: 'portfolio-bae40.firebasestorage.app',
    measurementId: 'G-TY67Q2MZ9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRHTLe7R1S81moJ5pacKrryrtICBb9_QI',
    appId: '1:774209885887:android:82383df1e162318902180a',
    messagingSenderId: '774209885887',
    projectId: 'portfolio-bae40',
    storageBucket: 'portfolio-bae40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcEUczolXBYiBarZcCe7ke8KAPu9utvgg',
    appId: '1:774209885887:ios:3ba8fa6301d5b76302180a',
    messagingSenderId: '774209885887',
    projectId: 'portfolio-bae40',
    storageBucket: 'portfolio-bae40.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );
}
